### ISSUE TITLE
Rewrite the makefile in order to handle many issues

### ISSUE THREAD

**Issue by jeonghanlee** [icshwi/e3-ADSupport#2]
* New version of ADSupport
* Clear way to select the system libraries or ADSupport libs
* have to check cross dependencies within libraries

**Comment by jeonghanlee** [comment]
- [x]  New version of ADSupport (R1-6)
- [x]  Clear way to select the system libraries or ADSupport libs 
- [x]  have to check cross dependencies within libraries
- [x]  Cross compilers (Yocto Linux)

**Comment by waynelewis** [comment]
Issue migrated to Gitlab: https://gitlab.esss.lu.se/e3/area/e3-ADSupport/-/issues/2
